---
##Cluster domain
dns_domain: "cluster.local"

##DNS server
dns_server_1: "8.8.8.8"
dns_server_2: "1.0.0.1"

##NTP Server
ntp_server_1: "time.google.com"
ntp_server_2: "ntp.ubuntu.com"

##IP Service CoreDNS
kubedns: "192.96.0.10"

##IP Master or LB for kubeconfig
kube_apiserver_ip: "94.74.114.129"

##IP of the master via internal_ip
INTERNAL_IP: "{{ internal_ip }}"

##IP range of the SVC in the cluster
SERVICE_CIDR: "192.96.0.0/16"

##IP range of the hosts(VM) in the cluster
CLUSTER_CIDR: "192.168.0.0/16"

##These're domain for generating the Certificartes.
KUBERNETES_HOSTNAMES: "kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"



