- name: pre-requisite
  hosts: all
  roles: 
    - pre-requisite

- name: init-master-node
  hosts: "{{groups['master'][0]}}"
  roles:
    - etcd
    - master-node

- name: init-worker-node
  hosts: worker
  roles:
    - worker-node

- name: "install calico"
  hosts: "{{groups['master'][0]}}"
  roles:
    - networking/calico-ds
    - networking/calico-systemd

- name: "install coredns"
  hosts: "{{groups['master'][0]}}"
  roles:
    - coredns