---
- name: "Install calicoctl"
  get_url:
    url: "https://github.com/projectcalico/calicoctl/releases/download/v3.20.4/{{ item }}"
    dest: /usr/local/bin/calicoctl
    mode: '0755'
    validate_certs: no
    timeout: 30
  retries: 5
  delay: 3
  register: get_url_result
  until: get_url_result is succeeded
  with_items:
    - calicoctl-linux-amd64

- name: "Make Directory calico-etcd"
  file:
    path: /etc/calico/etcd
    state: directory
    mode: 0755

- name: "Copy CA to /var/lib/kubernetes"
  copy:
    src: /var/lib/kubernetes/ca.pem
    dest: /etc/calico/etcd/etcd-ca
    remote_src: yes     

- name: "Copy Certificate to /var/lib/kubernetes"
  copy:
    src: /var/lib/kubernetes/kubernetes.pem
    dest: /etc/calico/etcd/etcd-cert
    remote_src: yes

- name: "Copy Key to /var/lib/kubernetes"
  copy:
    src: /var/lib/kubernetes/kubernetes-key.pem
    dest: /etc/calico/etcd/etcd-key
    remote_src: yes

- name: "Create calicoctl.cfg"
  copy:
    dest: "/etc/calico/calicoctl.cfg"
    content: |      
      apiVersion: projectcalico.org/v3
      kind: CalicoAPIConfig
      metadata:
      spec:
        etcdEndpoints: https://127.0.0.1:2379
        etcdKeyFile: /etc/calico/etcd/etcd-key
        etcdCertFile: /etc/calico/etcd/etcd-cert
        etcdCACertFile: /etc/calico/etcd/etcd-ca

- name: "Verify calico pods are running or not"
  command: |
    kubectl wait --namespace kube-system \
    --for=condition=ready pod \
    --selector=k8s-app=calico-node \
    --timeout=180s
  register: calico_results
  retries: 5
  delay: 5
  until: calico_results.rc == 0
  when: 
    - inventory_hostname == groups['master'][0]

- name: "Calicoctl patch felixconfiguration "
  command: |
    calicoctl patch felixconfiguration default --patch='{"spec": {"bpfKubeProxyIptablesCleanupEnabled": false}}'
  retries: 30
  delay: 5
  register: result
  until: result.rc == 0
  when: 
    - inventory_hostname == groups['master'][0]

- name: "Enable BPF Mode"
  command: |
    calicoctl patch felixconfiguration default --patch='{"spec": {"bpfEnabled": true}}'
  retries: 10
  delay: 5
  register: result
  until: result.rc == 0
  when: 
    - inventory_hostname == groups['master'][0]

