---
- name: "Include task gen-certificates"
  include_tasks: gen-cert.yml

- name: 'Generating the Data Encryption Config and Key'
  shell: |
    ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64)
    cat > encryption-config.yaml <<EOF
    kind: EncryptionConfig
    apiVersion: v1
    resources:
      - resources:
          - secrets
        providers:
          - aescbc:
              keys:
                - name: key1
                  secret: ${ENCRYPTION_KEY}
          - identity: {}
    EOF

    mkdir -p /var/lib/kubernetes/
    sudo mv encryption-config.yaml /var/lib/kubernetes/

- name: 'Bootstrapping an etcd Cluster Member'
  shell: |
    wget -q --show-progress --https-only --timestamping \
      "https://github.com/etcd-io/etcd/releases/download/v3.4.15/etcd-v3.4.15-linux-amd64.tar.gz"
      
    {
      tar -xvf etcd-v3.4.15-linux-amd64.tar.gz
      sudo mv etcd-v3.4.15-linux-amd64/etcd* /usr/local/bin/
    }

    {
      sudo mkdir -p /etc/etcd /var/lib/etcd
      sudo chmod 700 /var/lib/etcd
      sudo cp ca.pem kubernetes-key.pem kubernetes.pem /etc/etcd/
    }

    ETCD_NAME=$(hostname -s)

    cat <<EOF | sudo tee /etc/systemd/system/etcd.service
    [Unit]
    Description=etcd
    Documentation=https://github.com/coreos

    [Service]
    Type=notify
    ExecStart=/usr/local/bin/etcd \\
      --name ${ETCD_NAME} \\
      --cert-file=/etc/etcd/kubernetes.pem \\
      --key-file=/etc/etcd/kubernetes-key.pem \\
      --peer-cert-file=/etc/etcd/kubernetes.pem \\
      --peer-key-file=/etc/etcd/kubernetes-key.pem \\
      --trusted-ca-file=/etc/etcd/ca.pem \\
      --peer-trusted-ca-file=/etc/etcd/ca.pem \\
      --peer-client-cert-auth \\
      --client-cert-auth \\
      --initial-advertise-peer-urls https://{{ INTERNAL_IP }}:2380 \\
      --listen-peer-urls https://{{ INTERNAL_IP }}:2380 \\
      --listen-client-urls https://{{ INTERNAL_IP }}:2379,https://127.0.0.1:2379 \\
      --advertise-client-urls https://{{ INTERNAL_IP }}:2379 \\
      --data-dir=/var/lib/etcd
    Restart=on-failure
    RestartSec=5

    [Install]
    WantedBy=multi-user.target
    EOF

- name: 'Reload / Enable / start ETCD service'
  systemd:
    name: etcd.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: 'Verify etcd.serivce'
  command: |
    sudo ETCDCTL_API=3 etcdctl member list \
    --endpoints=https://127.0.0.1:2379 \
    --cacert=/etc/etcd/ca.pem \
    --cert=/etc/etcd/kubernetes.pem \
    --key=/etc/etcd/kubernetes-key.pem
  register: result

- debug:
    var: result
    verbosity: 2

