---
# - name: "Include task gen-certificates"
#   include_tasks: gen-cert.yml
#   when: 
#     - inventory_hostname == groups['master'][0]

- name: "Make Directory of ETCD "
  file:
    path: 
    - /var/lib/etcd
    - /etc/etcd
    state: directory
    mode: 0700

- name: "Make Directory of Kubernetes"
  file:
    path: /var/lib/kubernetes/
    state: directory
    mode: 0755

- name: 'Generating the Data Encryption Config and Key'
  shell: |
    ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64)
    cat > encryption-config.yaml <<EOF
    kind: EncryptionConfig
    apiVersion: v1
    resources:
      - resources:
          - secrets
        providers:
          - aescbc:
              keys:
                - name: key1
                  secret: ${ENCRYPTION_KEY}
          - identity: {}
    EOF

    sudo cp encryption-config.yaml /var/lib/kubernetes/


- name: Copy the Cert & Key file from master0 to master1-2 with PUSH method
  synchronize:
    src: "/root/{{ item }}"
    dest: "/etc/etcd/{{ item }}"
    mode: push
  delegate_to: "{{groups['master'][0]}}"
  with_items: 
    - 'ca.pem'
    - 'kubernetes.pem'
    - 'kubernetes-key.pem' 

- name: 'Bootstrapping an etcd Cluster Member'
  shell: |
    wget -q --show-progress --https-only --timestamping \
      "https://github.com/etcd-io/etcd/releases/download/v3.4.15/etcd-v3.4.15-linux-amd64.tar.gz"
      
    {
      tar -xvf etcd-v3.4.15-linux-amd64.tar.gz
      sudo mv etcd-v3.4.15-linux-amd64/etcd* /usr/local/bin/
    }

    ETCD_NAME=$(hostname -s)

- name: "Creating Single-ETCD Service"
  vars:
    HOST_COUNT: "{{ groups['etcd'] | length }}"
  template:
    src: single-etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'
  when:
    - HOST_COUNT == "1"
    - inventory_hostname == groups['etcd'][0]

- name: "Creating Multi-ETCD Service"
  vars:
    HOST_COUNT: "{{ groups['etcd'] | length }}"
  template:
    src: multi-etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'
  when:
    - HOST_COUNT == "3"

# - debug:
#     msg: HOST_COUNT


- name: 'Reload / Enable / start ETCD service'
  systemd:
    name: etcd.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: 'Verify etcd.serivce'
  command: |
    sudo ETCDCTL_API=3 etcdctl member list \
    --endpoints=https://127.0.0.1:2379 \
    --cacert=/etc/etcd/ca.pem \
    --cert=/etc/etcd/kubernetes.pem \
    --key=/etc/etcd/kubernetes-key.pem
  register: result

- debug:
    msg: result


