---
- name: "Using template CoreDNS Template"
  template:
    src: files/coredns.yml
    dest: /root/coredns.yml

- name: "Deploy CoreDNS"
  command: kubectl apply -f /root/coredns.yml

- name: "Download CoreDNS Binary file"   
  get_url:
    url: '{{ item }}'
    dest: /root
    validate_certs: no
    timeout: 30
  with_items:
    - https://github.com/coredns/coredns/releases/download/v1.8.3/coredns_1.8.3_linux_amd64.tgz

- name: "Download CoreDNS Binary file"
  shell: |
    tar -zxvf coredns_1.8.3_linux_amd64.tgz
    chmod +x coredns
    chown root:root coredns
    mv coredns /usr/local/bin



- name: "Add user coredns"
  user:
    name: "{{ item }}"
    system: no
    shell: /bin/false
    append: no
    create_home: yes
  with_items: ['coredns']

- name: "Create CoreDNS Folder"
  file:
    path: /etc/coredns
    mode: 0755
    state: directory

- name: Creating coredns Corefile
  copy:
    dest: "/etc/coredns/Corefile"
    mode: 0755
    content: |
      .:53 {
      bind 127.0.0.53
      prometheus :9153
      loadbalance
      cache {
                  success 65535 300 300
                  denial 65535 300 300
                  prefetch 10 5m 10%
      }
      template ANY AAAA {
          rcode NOERROR
      }
          forward . {{ dns_server_1 }} {{ dns_server_2 }} {
                    force_tcp
                    policy sequential
          }
      }
      cluster.local:53 {
      bind 127.0.0.53
      loadbalance
          forward . {{ kubedns }} {
                    force_tcp
          }
      }

- name: Creating coredns.service
  copy:
    dest: "/etc/systemd/system/coredns.service"
    content: |
      [Unit]
      Description=CoreDNS
      After=network.target

      [Service]
      LimitNPROC=1000000
      LimitNOFILE=1000000
      ExecStart=/usr/local/bin/coredns -conf /etc/coredns/Corefile
      Restart=always
      PermissionsStartOnly=true
      CapabilityBoundingSet=CAP_NET_BIND_SERVICE
      AmbientCapabilities=CAP_NET_BIND_SERVICE
      NoNewPrivileges=true
      User=coredns
      Group=coredns
      WorkingDirectory=/home/coredns
      ExecReload=/bin/kill -SIGUSR1 $MAINPID
      Restart=on-failure
      StandardOutput=file:/dev/null
      StandardError=file:/dev/null

      [Install]
      WantedBy=multi-user.target

- name: Start coredns
  systemd:
    name: coredns
    state: started
    enabled: yes
    daemon_reload: yes

- name: Creating /etc/resolv.conf
  copy:
    dest: "/etc/resolv.conf"
    content: |
      nameserver 127.0.0.53
      search svc.cluster.local cluster.local
      options timeout:5 attempts:1 single-request



